components:
 schemas:
  comment:
   type: object
   required:
    - commentID
    - commentContent
    - commentState
    - commentUser
    - commentPost
   properties:
    commentID:
     type: integer
     minimum: 0
    commentContent:
     type: string
     charLimit: 2000
    commentCreated:
     type: date-time
    commentEdited:
     type: date-time
    commentState:
     type: string
     enum: "OPEN", "RESTRICTED", "PRIVATE"
    commentUser:
     type: integer
     minimum: 0
    commentPost:
     type: integer
     minimum: 0