path:
 /project:
  post:
   tags:
    - project
   summary: create a new project
   operationId: project.create
   parameters:
    - name: projectName
      schema:
       type: string
       charLimit: 45
    - name: projectDescription
      schema:
       type: string
       charLimit: 500
    - name: projectVisibility
      schema:
       type: string
       enum: "OPEN", "RESTRICTED", "PRIVATE"
    - name: projectOwner
      schema:
       type: integer
       minimum: 0
#maybe post and user
 /project:
  get:
   tags:
    - project
   summary: returns all projects with visibility OPEN or RESTRICTED
   operationId: project.get_projects
   responses:
    '200':
     description: returns all projects found with visibility OPEN or RESTRICTED
     content:
      schema:
       type: array
       $ref: 'project.yml'
    '404':
     description: no projects found
 /project/{projectID}:
  get:
   tags:
    - project
   summary: return a project under ID
   operationId: project.get_by_id
   parameters:
    - name: projectID
      schema:
       type: integer
       minimum: 0
   responses:
    '200':
     description: return project found under id
     content:
      schema:
       type: array
       $ref: 'project.yml'
    '404':
     description: no project found under id
 /project/{projectID}/{userID}:
  get:
   tags:
    - project
   summary: return all users of project
   operationId: project.get_users_by_id
   parameters:
    - name: projectID
      schema:
       type: integer
       minimum: 0
   responses:
    '200':
     description: retun all users found under project
     content:
      schema:
       type: array
       $ref: 'user.yml'
    '404':
     description: no project found under id
    '405':     #Should in no way be possible
     description: no users found under project
 /project/{projectID}/post:
  get:
   tags:
    - project
   summary: return all posts of project
   operationId: project.get_posts_by_id
   parameters:
    - name: projectID
      schema:
       type: integer
       minimum: 0
   responses:
    '200':
     description: retun all posts found under project
     content:
      schema:
       type: array
       $ref: 'post.yml'
    '404':
     description: no project found under id
    '405':
     description: no posts found under project
 /project/{projectID}:
  put:
   tags:
    - project
   summary: update project settings of project found under id
   operationId: project.put_by_id
   parameters:
    - name: projectName
      schema:
       type: string
       charLimit: 45
    - name: description
      schema:
       type: string
       charLimit: 500
    - name: visibility
      schema:
       type: string
       enum: "OPEN", "RESTRICTED", "PRIVATE"
    responses:
     '404': 
      description: no project found under id
 /project/{projectID}/user:
  put:
   tags:
    - project
   summary: add user to project
   operationId: project.add_user_by_id
   parameters:
    - name: projectID
      schema:
       type: integer
       minimum: 0
    - name: userID
      schema:
       type: integer
       minimum: 0
    - name: role
      schema:#i dont know the roles
       type: string
       enum: "OWNER", "USER" 
   responses:
    '404':
     description: no user found under id
 /project/{projectID}:
  delete:
   tags:
    - project
   summary: delete project under id
   operationId: project.delete_by_id
   parameters:
    - name: projectID
      schema:
       type: integer
       minimum: 0
   responses:
    '404':
     description: no project found under id
 /project/{projectID)/(userID):
  delete:
   tags:
    - project
   summary: delete user under userid in project under projectid
   operationId: project.delete_user_by_id
   parameters:
    - name: projectID
      schema:
       type: integer
       minimum: 0
    - name: userID
      schema:
       type: integer
       minimum: 0
   responses:
    '404':
     description: no user found under id