components:
 schemas:
  project:
   type: object
   required:
    - projectID
    - projectName
    - projectOwner
    - projectVisibility
   properties:
    projectID:
     type: integer
     minimum: 0
    projectName:
     type: string
     charLimit: 45
    projectDescription:
     type: string
     charLimit: 500
    projectVisibility:
     type: string
     enum: "OPEN", "RESTRICTED", "PRIVATE"
    projectCreated
     type: date-time
    projectOwner:
     type: integer