components:
 schemas:
  user:
   type: object
   required:
    - userID
    - userName
   properties:
    userID:
     type: integer
     minimum: 0
    userName:
     type: string
     charLimit: 45
    userPass:
     type: password
     charLimit: 256
    userPicture:
     type: file
    userCreated:
     type: date-time